/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InterfazFormModifMetaData.java
 *
 * Created on 04-06-2013, 12:39:44 AM
 */
package busqlocalimage.Vista.BuscarImagen;

import Controlador.ControladorImagen;
import Entidades.Imagen;
import java.awt.Image;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.jvnet.substance.SubstanceLookAndFeel;
import org.jvnet.substance.button.StandardButtonShaper;

/**
 *
 * @author Alex
 */
public class InterfazFormModifMetaData extends javax.swing.JFrame {

    private ControladorImagen controladorImagen = new ControladorImagen();
    private static ArrayList<Imagen> arrayImagenResult;
    private ImageIcon icon;
    private int numTemp = 0;
    private String extDescrip;
    private String rutaImagen = null;

    /** Creates new form InterfazFormModifMetaData */
    public InterfazFormModifMetaData(ArrayList<Imagen> imagenResult) {
        initComponents();
        this.setLocation(500, 100);

        this.jButtonModificar.putClientProperty(SubstanceLookAndFeel.BUTTON_SHAPER_PROPERTY, new StandardButtonShaper());
        this.jButtonCancelar.putClientProperty(SubstanceLookAndFeel.BUTTON_SHAPER_PROPERTY, new StandardButtonShaper());

        arrayImagenResult = imagenResult;

        completarInfoImagen(numTemp);
        this.jLabelError.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelImagen = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jTextDimensiones = new javax.swing.JTextField();
        jTextTamano = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFormato = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFechaModif = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonCancelar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextDescrip = new javax.swing.JTextArea();
        jLabelError = new javax.swing.JLabel();
        jNext = new javax.swing.JLabel();
        jPrev = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SISC: Modificar MetaData de Imágenes");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setResizable(false);

        jLabelImagen.setText(" ");
        jLabelImagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelImagenMouseClicked(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Datos ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 14))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 13));
        jLabel4.setText("Nombre");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 13));
        jLabel5.setText("Dimensiones");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 13));
        jLabel6.setText("Tamaño");

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 13));
        jLabel7.setText("Extensión");

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 13));
        jLabel9.setText("Descripción");

        jTextNombre.setFont(new java.awt.Font("Calibri", 0, 12));
        jTextNombre.setText(" ");
        jTextNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombreActionPerformed(evt);
            }
        });

        jTextDimensiones.setEditable(false);
        jTextDimensiones.setFont(new java.awt.Font("Calibri", 0, 12));
        jTextDimensiones.setText(" ");
        jTextDimensiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDimensionesActionPerformed(evt);
            }
        });

        jTextTamano.setEditable(false);
        jTextTamano.setFont(new java.awt.Font("Calibri", 0, 12));
        jTextTamano.setText(" ");
        jTextTamano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTamanoActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 13));
        jLabel10.setText("KB");

        jTextFormato.setFont(new java.awt.Font("Calibri", 0, 12));
        jTextFormato.setText(" ");
        jTextFormato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFormatoActionPerformed(evt);
            }
        });
        jTextFormato.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTextFormatoInputMethodTextChanged(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 13));
        jLabel8.setText("Fecha Modificación");

        jTextFechaModif.setEditable(false);
        jTextFechaModif.setFont(new java.awt.Font("Calibri", 0, 12));
        jTextFechaModif.setText(" ");
        jTextFechaModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFechaModifActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("Calibri", 0, 12));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonModificar.setFont(new java.awt.Font("Calibri", 0, 12));
        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setFont(new java.awt.Font("Calibri", 0, 11));

        jTextDescrip.setColumns(20);
        jTextDescrip.setFont(new java.awt.Font("Calibri", 0, 11));
        jTextDescrip.setRows(5);
        jTextDescrip.setText(" ");
        jScrollPane1.setViewportView(jTextDescrip);

        jLabelError.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabelError.setForeground(new java.awt.Color(255, 0, 0));
        jLabelError.setText("Error");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGap(4, 4, 4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextDimensiones, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                    .addComponent(jTextNombre)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTextFormato, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextTamano, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFechaModif, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelError, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonModificar))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextDimensiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextTamano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFormato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFechaModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonModificar)
                    .addComponent(jLabelError))
                .addContainerGap())
        );

        jNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busqlocalimage/Imagenes/arrow-right-icon-48px.png"))); // NOI18N
        jNext.setText(" ");
        jNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jNextMouseClicked(evt);
            }
        });

        jPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busqlocalimage/Imagenes/arrow-left-icon-48px.png"))); // NOI18N
        jPrev.setText(" ");
        jPrev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPrevMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPrev)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jLabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jNext)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNext)
                    .addComponent(jPrev)
                    .addComponent(jLabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombreActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextNombreActionPerformed

    private void jTextDimensionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDimensionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDimensionesActionPerformed

    private void jTextTamanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTamanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTamanoActionPerformed

    private void jTextFormatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFormatoActionPerformed

        System.out.println("Ext Antes ==> " + extDescrip);
        System.out.println("Lo nuevo ==> " + this.jTextFormato.getText().trim());

        if (!extDescrip.equals(this.jTextFormato.getText().trim())) {

            JOptionPane.showMessageDialog(null, "ha cambiado el texto");
            System.out.println("Ha cambiado el texto!");
        } else {

            System.out.println("No se cambio!");
        }

    }//GEN-LAST:event_jTextFormatoActionPerformed

    private void jTextFechaModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFechaModifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFechaModifActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        setearElementos();
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNextMouseClicked

        numTemp = numTemp + 1;
        if (numTemp < arrayImagenResult.size()) {

            completarInfoImagen(numTemp);
            jNext.setVisible(true);
        } else {

            //jNext.setVisible(false);
            numTemp = (arrayImagenResult.size()) - 1;
        }

    }//GEN-LAST:event_jNextMouseClicked

    private void jPrevMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPrevMouseClicked

        numTemp = numTemp - 1;
        if (numTemp >= 0) {

            completarInfoImagen(numTemp);
            jPrev.setVisible(true);
        } else {

            //jPrev.setVisible(false);
            numTemp = 0;
        }


    }//GEN-LAST:event_jPrevMouseClicked

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed

        rutaImagen = (arrayImagenResult.get(numTemp).getRuta());
        String nombreImagen = arrayImagenResult.get(numTemp).getNombre();

        String nameImagen = (arrayImagenResult.get(numTemp).getNombre()).replace(".jpg", "");

        String nameOrig = nameImagen.trim();
        String extOrig = (arrayImagenResult.get(numTemp).getFormato()).trim();
        extDescrip = (arrayImagenResult.get(numTemp).getDescrip()).trim();

        String newName = this.jTextNombre.getText().trim();
        String newExt = this.jTextFormato.getText().trim();
        String newDescrip = this.jTextDescrip.getText().trim();


        if (!nameOrig.equals(newName) || !extOrig.equals(newExt) || !extDescrip.equals(newDescrip)) {

            if (extOrig.equals(newExt)) {

                newExt = ".jpg";
            } else {

                newExt = "." + this.jTextFormato.getText();
            }

            if (!nameOrig.equals(newName) || !extOrig.equals(newExt)) {

                controladorImagen.renombrarImagen(rutaImagen, nombreImagen, newName, newExt);
                this.jLabelError.setText("Archivo Renombrado!");
                this.jLabelError.setVisible(true);

                arrayImagenResult.get(numTemp).setNombre(newName.concat(newExt));
                rutaImagen = rutaImagen.replace(nombreImagen, newName.concat(newExt));

                arrayImagenResult.get(numTemp).setRuta(rutaImagen);
                arrayImagenResult.get(numTemp).setFormato(this.jTextFormato.getText());

                jPanelBuscarImagenResultadosLista.mostrarDatos(arrayImagenResult);
                jPanelBuscarImagenResultadosVista.mostrarDatos(arrayImagenResult);

                this.dispose();
            }

            if (!extDescrip.equals(newDescrip)) {

                icon.setDescription("Holalalalalala");
            }
        }

    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jTextFormatoInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextFormatoInputMethodTextChanged
    }//GEN-LAST:event_jTextFormatoInputMethodTextChanged

    private void jLabelImagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelImagenMouseClicked

        if (rutaImagen != null) {

            try {

                Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + rutaImagen);
            } catch (IOException ex) {

                Logger.getLogger(jPanelBuscarImagen.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jLabelImagenMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.OfficeSilver2007Skin");
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new InterfazFormModifMetaData(arrayImagenResult).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private static javax.swing.JLabel jLabelError;
    private static javax.swing.JLabel jLabelImagen;
    private javax.swing.JLabel jNext;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jPrev;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private static javax.swing.JTextArea jTextDescrip;
    private static javax.swing.JTextField jTextDimensiones;
    private static javax.swing.JTextField jTextFechaModif;
    private static javax.swing.JTextField jTextFormato;
    private static javax.swing.JTextField jTextNombre;
    private static javax.swing.JTextField jTextTamano;
    // End of variables declaration//GEN-END:variables

    private void completarInfoImagen(int num) {

        icon = new ImageIcon(arrayImagenResult.get(num).getRuta());
        vistaImagen(icon);

        String nameImagen = (arrayImagenResult.get(num).getNombre()).replace(".jpg", "");

        this.jTextNombre.setText(nameImagen.trim());
        this.jTextTamano.setText(String.valueOf(arrayImagenResult.get(num).getTamano()));
        this.jTextFormato.setText(arrayImagenResult.get(num).getFormato());
        this.jTextFechaModif.setText(arrayImagenResult.get(num).getFechaModif());
        this.jTextDimensiones.setText(arrayImagenResult.get(num).getDimensiones());
        this.jTextDescrip.setText(arrayImagenResult.get(num).getDescrip());
    }//fin metodo completar info de imágenes

    private void vistaImagen(ImageIcon icon) {

        /*Imagen en jLabel*/
        Image img = icon.getImage();
        Image newimg = img.getScaledInstance(132, 139, java.awt.Image.SCALE_SMOOTH);
        ImageIcon newIcon = new ImageIcon(newimg);

        jLabelImagen.setIcon(newIcon);
        jLabelImagen.setSize(132, 139);
    }//Fin metodo imagenDefault

    public static void setearElementos() {

        jLabelImagen.setText("");
        jTextNombre.setText("");
        jTextDimensiones.setText("");
        jTextTamano.setText("");
        jTextFormato.setText("");
        jTextFechaModif.setText("");
        jTextDescrip.setText("");
        jLabelError.setVisible(false);
    }//Fin metodo setear Elementos
}
