/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jPanelBuscarImagenResultadosVista.java
 *
 * Created on 04-06-2013, 12:09:46 AM
 */
package busqlocalimage.Vista.BuscarImagen;

import Entidades.Imagen;
import java.awt.Image;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Alex
 */
public class jPanelBuscarImagenResultadosVista extends javax.swing.JPanel {

    private static ArrayList<Imagen> imageResult = new ArrayList<Imagen>();
    private static ImageIcon icon;
    private int a = 0;
    private int b = 1;
    private int c = 2;
    private int d = 3;
    private static String rutaImagen = null;
    private int temp = 0;

    /** Creates new form jPanelBuscarImagenResultadosVista */
    @SuppressWarnings("static-access")
    public jPanelBuscarImagenResultadosVista() {

        initComponents();

        setearElementos();

        this.imagePrev.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePrev = new javax.swing.JLabel();
        jPanelImagen1 = new javax.swing.JPanel();
        Imagen1 = new javax.swing.JLabel();
        jPanelImagen2 = new javax.swing.JPanel();
        Imagen2 = new javax.swing.JLabel();
        jPanelImagen3 = new javax.swing.JPanel();
        Imagen3 = new javax.swing.JLabel();
        jPanelImagen4 = new javax.swing.JPanel();
        Imagen4 = new javax.swing.JLabel();
        imageNext = new javax.swing.JLabel();
        jLabelDist4 = new javax.swing.JLabel();
        jLabelDist3 = new javax.swing.JLabel();
        jLabelDist2 = new javax.swing.JLabel();
        jLabelDist1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagePrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busqlocalimage/Imagenes/Button-Previous-icon.png"))); // NOI18N
        imagePrev.setText(" ");
        imagePrev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                imagePrevMousePressed(evt);
            }
        });
        add(imagePrev, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 25, 27));

        jPanelImagen1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        Imagen1.setText("Imagen 1");
        Imagen1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Imagen1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Imagen1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelImagen1Layout = new javax.swing.GroupLayout(jPanelImagen1);
        jPanelImagen1.setLayout(jPanelImagen1Layout);
        jPanelImagen1Layout.setHorizontalGroup(
            jPanelImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Imagen1, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
        );
        jPanelImagen1Layout.setVerticalGroup(
            jPanelImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Imagen1, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
        );

        add(jPanelImagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanelImagen2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        Imagen2.setText("Imagen 2");
        Imagen2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Imagen2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelImagen2Layout = new javax.swing.GroupLayout(jPanelImagen2);
        jPanelImagen2.setLayout(jPanelImagen2Layout);
        jPanelImagen2Layout.setHorizontalGroup(
            jPanelImagen2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Imagen2, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
        );
        jPanelImagen2Layout.setVerticalGroup(
            jPanelImagen2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Imagen2, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
        );

        add(jPanelImagen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        jPanelImagen3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        Imagen3.setText("Imagen 3");
        Imagen3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Imagen3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelImagen3Layout = new javax.swing.GroupLayout(jPanelImagen3);
        jPanelImagen3.setLayout(jPanelImagen3Layout);
        jPanelImagen3Layout.setHorizontalGroup(
            jPanelImagen3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Imagen3, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
        );
        jPanelImagen3Layout.setVerticalGroup(
            jPanelImagen3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Imagen3, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
        );

        add(jPanelImagen3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        jPanelImagen4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        Imagen4.setText("Imagen 4");
        Imagen4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Imagen4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelImagen4Layout = new javax.swing.GroupLayout(jPanelImagen4);
        jPanelImagen4.setLayout(jPanelImagen4Layout);
        jPanelImagen4Layout.setHorizontalGroup(
            jPanelImagen4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Imagen4, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
        );
        jPanelImagen4Layout.setVerticalGroup(
            jPanelImagen4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Imagen4, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
        );

        add(jPanelImagen4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        imageNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busqlocalimage/Imagenes/Button-Next-icon.png"))); // NOI18N
        imageNext.setText(" ");
        imageNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                imageNextMousePressed(evt);
            }
        });
        add(imageNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, 25, 27));

        jLabelDist4.setFont(new java.awt.Font("Calibri", 0, 11));
        jLabelDist4.setText("distancia Imagen 4");
        add(jLabelDist4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, -1, -1));

        jLabelDist3.setFont(new java.awt.Font("Calibri", 0, 11));
        jLabelDist3.setText("distancia Imagen 3");
        add(jLabelDist3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));

        jLabelDist2.setFont(new java.awt.Font("Calibri", 0, 11));
        jLabelDist2.setText("distancia Imagen 2");
        add(jLabelDist2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));

        jLabelDist1.setFont(new java.awt.Font("Calibri", 0, 11));
        jLabelDist1.setText("distancia Imagen 1");
        add(jLabelDist1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void Imagen1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Imagen1MousePressed
    }//GEN-LAST:event_Imagen1MousePressed

    private void imagePrevMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagePrevMousePressed

        temp--;
        this.imageNext.setVisible(true);

        if (temp == 0) {

            this.imagePrev.setVisible(false);
        } else {

            this.imagePrev.setVisible(true);
        }

        a -= 1;
        b -= 1;
        c -= 1;
        d -= 1;

        deslizarImagen(a, b, c, d);
    }//GEN-LAST:event_imagePrevMousePressed

    private void imageNextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageNextMousePressed

        temp++;
        this.imagePrev.setVisible(true);

        if (temp == (imageResult.size() - 4)) {

            this.imageNext.setVisible(false);
        } else {

            this.imageNext.setVisible(true);
        }

        a += 1;
        b += 1;
        c += 1;
        d += 1;

        deslizarImagen(a, b, c, d);
    }//GEN-LAST:event_imageNextMousePressed

    private void Imagen1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Imagen1MouseClicked

        rutaImagen = getRuta(a);

        abrirImagen();
    }//GEN-LAST:event_Imagen1MouseClicked

    private void Imagen2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Imagen2MouseClicked

        rutaImagen = getRuta(b);

        abrirImagen();
    }//GEN-LAST:event_Imagen2MouseClicked

    private void Imagen3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Imagen3MouseClicked

        rutaImagen = getRuta(c);

        abrirImagen();
    }//GEN-LAST:event_Imagen3MouseClicked

    private void Imagen4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Imagen4MouseClicked

        rutaImagen = getRuta(d);

        abrirImagen();
    }//GEN-LAST:event_Imagen4MouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JLabel Imagen1;
    private static javax.swing.JLabel Imagen2;
    private static javax.swing.JLabel Imagen3;
    private static javax.swing.JLabel Imagen4;
    private static javax.swing.JLabel imageNext;
    private static javax.swing.JLabel imagePrev;
    private static javax.swing.JLabel jLabelDist1;
    private static javax.swing.JLabel jLabelDist2;
    private static javax.swing.JLabel jLabelDist3;
    private static javax.swing.JLabel jLabelDist4;
    private static javax.swing.JPanel jPanelImagen1;
    private static javax.swing.JPanel jPanelImagen2;
    private static javax.swing.JPanel jPanelImagen3;
    private static javax.swing.JPanel jPanelImagen4;
    // End of variables declaration//GEN-END:variables

    public static void mostrarDatos(ArrayList<Imagen> arrayImageResult) {

        imageNext.setVisible(true);
        imageResult = arrayImageResult;

        if (getPreview(0) != null) {

            Imagen1.setVisible(true);
            Imagen1.setIcon(getPreview(0));
            jPanelImagen1.setVisible(true);
            jLabelDist1.setText(getDistance(0));
            imageNext.setVisible(true);

            Imagen1.setToolTipText(getRuta(0));

        } else {

            Imagen1.setVisible(false);
            jPanelImagen1.setVisible(false);
            jLabelDist1.setText("");
            imageNext.setVisible(false);
        }

        if (getPreview(1) != null) {

            Imagen2.setVisible(true);
            Imagen2.setIcon(getPreview(1));
            jPanelImagen2.setVisible(true);
            jLabelDist2.setText(getDistance(1));
            imageNext.setVisible(true);

            Imagen2.setToolTipText(getRuta(1));

        }

        if (getPreview(2) != null) {

            Imagen3.setVisible(true);
            Imagen3.setIcon(getPreview(2));
            jPanelImagen3.setVisible(true);
            jLabelDist3.setText(getDistance(2));
            imageNext.setVisible(true);

            Imagen3.setToolTipText(getRuta(2));

        }

        if (getPreview(3) != null) {

            Imagen4.setVisible(true);
            Imagen4.setIcon(getPreview(3));
            jPanelImagen4.setVisible(true);
            jLabelDist4.setText(getDistance(3));
            imageNext.setVisible(true);

            Imagen4.setToolTipText(getRuta(3));

        }

    }

    private static String getRuta(int num) {

        String rutaImagen = "";
        if (num >= 0 & num < imageResult.size()) {

            rutaImagen = imageResult.get(num).getRuta();
            return rutaImagen;
        } else {

            rutaImagen = null;
            return rutaImagen;
        }
    }//Fin metodo extracción de Ruta

    private static Icon getPreview(int num) {

        if (num >= 0 & num < imageResult.size()) {

            icon = new ImageIcon(imageResult.get(num).getRuta());
            Image img = icon.getImage();
            Image newimg = img.getScaledInstance(108, 107, java.awt.Image.SCALE_SMOOTH);

            return new ImageIcon(newimg);
        } else {

            return null;
        }
    }//Fin metodo

    private static String getDistance(int num) {

        if (num >= 0 & num < imageResult.size()) {

            double distancia = imageResult.get(num).getDistancia();
            String distance = "d = " + String.valueOf(distancia);

            return distance;
        } else {

            String distance = "";
            return distance;
        }
    }//Fin metodo getDistance

    public static void setearElementos() {

        imagePrev.setVisible(false);
        imageNext.setVisible(false);

        Imagen1.setText("");
        Imagen2.setText("");
        Imagen3.setText("");
        Imagen4.setText("");

        Imagen1.setToolTipText(null);
        Imagen2.setToolTipText(null);
        Imagen3.setToolTipText(null);
        Imagen4.setToolTipText(null);

        jLabelDist1.setText("");
        jLabelDist2.setText("");
        jLabelDist3.setText("");
        jLabelDist4.setText("");

        Imagen1.setIcon(null);
        Imagen2.setIcon(null);
        Imagen3.setIcon(null);
        Imagen4.setIcon(null);

        rutaImagen = null;
    }//Fin metodo setear elementos

    private void deslizarImagen(int a, int b, int c, int d) {

        Imagen1.setIcon(getPreview(a));
        Imagen2.setIcon(getPreview(b));
        Imagen3.setIcon(getPreview(c));
        Imagen4.setIcon(getPreview(d));

        jLabelDist1.setText(getDistance(a));
        jLabelDist2.setText(getDistance(b));
        jLabelDist3.setText(getDistance(c));
        jLabelDist4.setText(getDistance(d));

        Imagen1.setToolTipText(getRuta(a));
        Imagen2.setToolTipText(getRuta(b));
        Imagen3.setToolTipText(getRuta(c));
        Imagen4.setToolTipText(getRuta(d));
    }//Fin metodo deslizar imágenes

    private void abrirImagen() {

        if (rutaImagen != null) {
            try {

                Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + rutaImagen);
            } catch (IOException ex) {

                Logger.getLogger(jPanelBuscarImagen.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//Fin comando abrir imagen
}


