/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jPanelComoFunciona.java
 *
 * Created on 27-08-2013, 10:40:40 AM
 */
package busqlocalimage.Vista.AyudaSistema;

/**
 *
 * @author Alex
 */
public class jPanelComoFuncionaPag_2 extends javax.swing.JPanel {

    private String rutaImagen;

    /** Creates new form jPanelComoFunciona */
    public jPanelComoFuncionaPag_2() {
        initComponents();

        this.jTextArea1.setFocusable(false);
        this.jLabelFig1.setToolTipText("Click para Agrandar Imagen.");
        this.jLabelFig2.setToolTipText("Click para Agrandar Imagen.");

        this.jTextArea1.setToolTipText("");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabelFig1 = new javax.swing.JLabel();
        jLabelFig2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busqlocalimage/Imagenes/logo_Como Utilizar SISC peque.png"))); // NOI18N
        jLabel1.setText(" ");

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setFont(new java.awt.Font("Calibri", 0, 12));
        jTextArea1.setRows(2);
        jTextArea1.setText("    SISC permite la búsqueda de imágenes por contenido , mediante un formulario que se le presenta al \nusuario en la opción \"Buscar Imagen\", presente en la interfaz de menú. El formulario de búsqueda, \ncomo se muestra en la Figura 1, debe ser ingresado en su totalidad por el usuario para ejecutar la \ncomparación de similitudes entre las imágenes dentro de un repositorio. Además, adicional a la bús-\nqueda permite al usuario crear rutas favoritas, cómo se muestra en la Figura 2,  donde se insertan \ncarpetas de imágenes para facilitar y acotar el sector donde implementar la comparación de imágenes.\n\n");
        jTextArea1.setToolTipText("");
        jTextArea1.setBorder(null);
        jTextArea1.setMargin(new java.awt.Insets(3, 2, 2, 1));
        jTextArea1.setOpaque(false);
        jScrollPane1.setViewportView(jTextArea1);

        jLabelFig1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busqlocalimage/Imagenes/formBuscarImagen_peque.png"))); // NOI18N
        jLabelFig1.setText(" ");
        jLabelFig1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFig1MouseClicked(evt);
            }
        });

        jLabelFig2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busqlocalimage/Imagenes/formRutasFav_peque.png"))); // NOI18N
        jLabelFig2.setText(" ");
        jLabelFig2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFig2MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 11));
        jLabel4.setText("Figura 1: Formulario de Búsqueda");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 11));
        jLabel5.setText("Figura 2: Rutas Favoritas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(476, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFig1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabelFig2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(94, 94, 94)))
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFig1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFig2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelFig1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFig1MouseClicked

        rutaImagen = "/busqlocalimage/Imagenes/CapturaBusq.PNG";
        new vistaMaxFiguras(rutaImagen).setVisible(true);
    }//GEN-LAST:event_jLabelFig1MouseClicked

    private void jLabelFig2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFig2MouseClicked

        rutaImagen = "/busqlocalimage/Imagenes/CapturaRF.PNG";
        new vistaMaxFiguras(rutaImagen).setVisible(true);
    }//GEN-LAST:event_jLabelFig2MouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelFig1;
    private javax.swing.JLabel jLabelFig2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
