/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jPanelComoFunciona.java
 *
 * Created on 28-08-2013, 05:27:00 PM
 */
package busqlocalimage.Vista.AyudaSistema;

import Logica.LiberarMemoria;
import busqlocalimage.Vista.InterfazBienvenida;
import java.awt.CardLayout;
import javax.swing.SwingUtilities;

/**
 *
 * @author Alex
 */
public class jPanelComoFunciona extends javax.swing.JPanel {

    private static CardLayout cambiarPanelAyuda = null;
    private int temp = 1;

    /** Creates new form jPanelComoFunciona */
    public jPanelComoFunciona() {
        initComponents();

        new LiberarMemoria();

        cambiarPanelAyuda = (CardLayout) panelContenedor.getLayout();
        this.jButton1.setVisible(false);

        setearPanel();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContenedor = new javax.swing.JPanel();
        jPanelComoFuncionaPag_11 = new busqlocalimage.Vista.AyudaSistema.jPanelComoFuncionaPag_1();
        jPanelComoFuncionaPag_21 = new busqlocalimage.Vista.AyudaSistema.jPanelComoFuncionaPag_2();
        jPanelComoFuncionaPag_31 = new busqlocalimage.Vista.AyudaSistema.jPanelComoFuncionaPag_3();
        jPanelComoFuncionaPag_41 = new busqlocalimage.Vista.AyudaSistema.jPanelComoFuncionaPag_5();
        jPanelComoFuncionaPag_42 = new busqlocalimage.Vista.AyudaSistema.jPanelComoFuncionaPag_4();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                formAncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        panelContenedor.setLayout(new java.awt.CardLayout());
        panelContenedor.add(jPanelComoFuncionaPag_11, "cardPage1");
        panelContenedor.add(jPanelComoFuncionaPag_21, "cardPage2");
        panelContenedor.add(jPanelComoFuncionaPag_31, "cardPage3");
        panelContenedor.add(jPanelComoFuncionaPag_41, "cardPage5");
        panelContenedor.add(jPanelComoFuncionaPag_42, "cardPage4");

        jButton1.setText("Anterior");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Siguiente");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 482, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        temp--;

        if (temp == 1) {

            cambiarPanel("cardPage1");
            this.jButton1.setVisible(false);
        } else if (temp == 2) {

            cambiarPanel("cardPage2");
        } else if (temp == 3) {

            cambiarPanel("cardPage3");
        } else if (temp == 4) {

            cambiarPanel("cardPage4");
            this.jButton2.setVisible(true);
            this.jButton2.setText("Siguiente");
        } else if (temp == 5) {

            cambiarPanel("cardPage5");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        temp++;

        if (temp == 1) {

            cambiarPanel("cardPage1");
        } else if (temp == 2) {

            cambiarPanel("cardPage2");
            this.jButton1.setVisible(true);
        } else if (temp == 3) {

            cambiarPanel("cardPage3");
        } else if (temp == 4) {

            cambiarPanel("cardPage4");
        } else if (temp == 5) {

            cambiarPanel("cardPage5");
            //this.jButton2.setVisible(false);
            this.jButton2.setText("Finalizar");
        } else if (temp == 6) {

            SwingUtilities.getWindowAncestor(this).dispose();
            new InterfazBienvenida().setVisible(true);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void formAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorMoved
    }//GEN-LAST:event_formAncestorMoved

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        temp = 1;
        setearPanel();
    }//GEN-LAST:event_formComponentShown
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private busqlocalimage.Vista.AyudaSistema.jPanelComoFuncionaPag_1 jPanelComoFuncionaPag_11;
    private busqlocalimage.Vista.AyudaSistema.jPanelComoFuncionaPag_2 jPanelComoFuncionaPag_21;
    private busqlocalimage.Vista.AyudaSistema.jPanelComoFuncionaPag_3 jPanelComoFuncionaPag_31;
    private busqlocalimage.Vista.AyudaSistema.jPanelComoFuncionaPag_5 jPanelComoFuncionaPag_41;
    private busqlocalimage.Vista.AyudaSistema.jPanelComoFuncionaPag_4 jPanelComoFuncionaPag_42;
    private static javax.swing.JPanel panelContenedor;
    // End of variables declaration//GEN-END:variables

    /*Metodo para generar el cambio de paneles*/
    public static void cambiarPanel(String panel) {

        cambiarPanelAyuda.show(panelContenedor, panel);
    }//Fin metodo

    public void setearPanel() {

        cambiarPanel("cardPage1");
    }//Fin metodo
}
