/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jPanelListarRutasFavoritas.java
 *
 * Created on 08-06-2013, 05:25:39 PM
 */
package busqlocalimage.Vista.RutasFavoritas;

import Entidades.RutaFavorita;
import java.util.ArrayList;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alex
 */
public class jPanelListarRutasFavoritas extends javax.swing.JPanel {

    private static ArrayList<RutaFavorita> rutaFavorita;
    private static String[] columNames = {"ID Ruta Favorita", "Nombre", "Cantidad de Imágenes", "Fecha de Creación"};
    private int numFila = 0;

    /** Creates new form jPanelListarRutasFavoritas */
    public jPanelListarRutasFavoritas() {
        initComponents();

        jTable1.setModel(new DefaultTableModel(columNames, 0));
        //fijarAnchoTabla();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jScrollPane1.setFont(new java.awt.Font("Calibri", 0, 12));

        jTable1.setFont(new java.awt.Font("Calibri", 0, 12));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Cantidad de Imágenes", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable1MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setResizable(false);
        jTable1.getColumnModel().getColumn(1).setResizable(false);
        jTable1.getColumnModel().getColumn(2).setResizable(false);
        jTable1.getColumnModel().getColumn(3).setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        selectRow();

    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
    }//GEN-LAST:event_jTable1MousePressed

    private void jTable1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseEntered
    }//GEN-LAST:event_jTable1MouseEntered
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    /*Modelo de la Tabla*/
    private static void Modelo() {
        jTable1.setModel(new javax.swing.table.DefaultTableModel(columNames, rutaFavorita.size()) {

            Class[] types = new Class[]{Integer.class, String.class, Integer.class, String.class};

            @Override
            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
            boolean[] canEdit = new boolean[]{
                false, false, false, false
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
    }

    public static void mostrarDatos(ArrayList<RutaFavorita> rutaFavoritaEnv) {

        rutaFavorita = rutaFavoritaEnv;
        Modelo();
        for (int i = 0; i < rutaFavorita.size(); i++) {
            jTable1.setValueAt((i + 1), i, 0);
            jTable1.setValueAt(rutaFavorita.get(i).getNombre(), i, 1);
            jTable1.setValueAt(rutaFavorita.get(i).getCantImagenes(), i, 2);
            jTable1.setValueAt(rutaFavorita.get(i).getFechaCreacion(), i, 3);
        }
    }//Fin metodo

    private static void fijarAnchoTabla() {

        DefaultTableCellRenderer modelocentrar = new DefaultTableCellRenderer();
        modelocentrar.setHorizontalAlignment(SwingConstants.CENTER);

        int[] anchos = {20, 20, 50, 40};
        for (int i = 0; i < anchos.length; i++) {

            jTable1.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
            jTable1.getColumnModel().getColumn(i).setMinWidth(anchos[i]);
            jTable1.getColumnModel().getColumn(i).setMaxWidth(anchos[i]);
            jTable1.getColumnModel().getColumn(i).setWidth(anchos[i]);

            jTable1.getColumnModel().getColumn(i).setCellRenderer(modelocentrar);
            jTable1.getColumnModel().getColumn(i).setResizable(false);
        }
    }//Fin fijar ancho jTable

    /*Al clickear en la tabla*/
    @SuppressWarnings("static-access")
    private void selectRow() {

        numFila = this.jTable1.getSelectedRow();
        jPanelRutasFavoritas.setRowLista(numFila);
    }
}
